
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MRX
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        kubus2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bola2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bola = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        balok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Program Penghitung Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 30, 230, 14);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 100, 5, 5);

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 40, 160, 14);

        kubus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kubus2ActionPerformed(evt);
            }
        });
        jPanel2.add(kubus2);
        kubus2.setBounds(40, 70, 120, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("cm");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(180, 80, 17, 14);

        kubus.setText("Volume");
        kubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kubusActionPerformed(evt);
            }
        });
        jPanel2.add(kubus);
        kubus.setBounds(40, 140, 110, 23);

        jTabbedPane2.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        bola2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bola2ActionPerformed(evt);
            }
        });
        jPanel3.add(bola2);
        bola2.setBounds(40, 70, 120, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Masukkan Panjang Jari-jari");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 40, 160, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(180, 80, 17, 14);

        bola.setText("Volume");
        bola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolaActionPerformed(evt);
            }
        });
        jPanel3.add(bola);
        bola.setBounds(40, 140, 110, 23);

        jTabbedPane2.addTab("Bola", jPanel3);

        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Panjang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 110, 14);

        pj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjActionPerformed(evt);
            }
        });
        jPanel1.add(pj);
        pj.setBounds(130, 10, 160, 30);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 20, 30, 20);
        jPanel1.add(lb);
        lb.setBounds(130, 80, 160, 30);

        jLabel3.setText("Masukkan Lebar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 77, 14);

        jLabel4.setText("Masukkan Tinggi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 160, 78, 14);
        jPanel1.add(tg);
        tg.setBounds(130, 150, 160, 30);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 160, 40, 20);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 90, 40, 20);

        balok.setText("volume");
        balok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balokActionPerformed(evt);
            }
        });
        jPanel1.add(balok);
        balok.setBounds(130, 220, 160, 23);

        jTabbedPane2.addTab("Balok", jPanel1);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 60, 620, 460);

        setBounds(0, 0, 654, 562);
    }// </editor-fold>//GEN-END:initComponents

    private void bola2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bola2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bola2ActionPerformed

    private void balokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balokActionPerformed
        int panjang,lebar, tinggi;
        panjang=Integer.parseInt(pj.getText());
        lebar=Integer.parseInt(lb.getText());
        tinggi=Integer.parseInt(tg.getText());
        int hasil=panjang*lebar*tinggi;
        try {
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_balokActionPerformed

    private void kubus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kubus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kubus2ActionPerformed

    private void kubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kubusActionPerformed
        int sisi;
        sisi=Integer.parseInt(kubus2.getText());
        int hasil=sisi*sisi*sisi;
        
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah :"
                +hasil,"volume",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_kubusActionPerformed

    private void bolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolaActionPerformed
        float jari;
        jari=Integer.parseInt(bola2.getText());
        float hasil1=(float) (4/3*Math.PI*jari*jari*jari);
        try {
            JOptionPane.showMessageDialog(null,"Volume Permukaan Bola Adalah :"
            +hasil1,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bolaActionPerformed

    private void pjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balok;
    private javax.swing.JButton bola;
    private javax.swing.JTextField bola2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton kubus;
    private javax.swing.JTextField kubus2;
    private javax.swing.JTextField lb;
    private javax.swing.JTextField pj;
    private javax.swing.JTextField tg;
    // End of variables declaration//GEN-END:variables
}
